version: '3'
services:
  docker-app:
    image: docker-app:0.0.1
    build: .
    restart: on-failure
    ports:
      - 3000
    environment:
      MONGO_URL: mongodb://mongo/mydb
      REDIS_HOST: redis
    labels:
      - "traefik.frontend.rule=Host:192.168.99.100"
    depends_on:
      - mongo
    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.0.4

  redis:
    image: redis
    ports:
      - 6379:6379

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  